config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  #redirect('/events')
  resources :events
  resources :attendances
  get '/users', to: 'users#show'
  

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances

  #validates_comparison_of :start_date, greater_than: :Date.today, presence: true
  validates :duration, presence: true, numericality: {divisible_by: 5}
  validates :title, presence: true, length: {minimum: 5, maximum: 140}
  validates :description, presence: true, length: {minimum: 20, maximum: 1000}
  validates_comparison_of :price, presence: true, greater_than_or_equal_to: 1
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
       
  # after_create :welcome_send
  #   def welcome_send
  #            UserMailer.welcome_email(self).deliver_now
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:stripe_customer_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_administrator

  def show
    @user = User.find(params[:format])
  end

private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter !"
      redirect_to new_user_session_path
    end
  end

  def authenticate_administrator
    unless current_user == User.find(params[:format])
      flash[:alert] = "Vous ne pouvez accéder qu'à votre profil"
      redirect_to root_path
    end
  end
end
# def show
  #   @user = User.find(params[:format]) #peut être qu'il faudra remettre id un jour !!!!!
  # end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_attendance.html.erb
<div id="<%= dom_id attendance %>">
  <p>
    <strong>Stripe customer:</strong>
    <%= attendance.stripe_customer_id %>
  </p>

</div>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stripe_customer_id, style: "display: block" %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Show this attendance", @attendance %> |
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendances</h1>

<div id="attendances">
  <% @attendances.each do |attendance| %>
    <%= render attendance %>
    <p>
      <%= link_to "Show this attendance", attendance %>
    </p>
  <% end %>
</div>

<%= link_to "New attendance", new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendance %>

<div>
  <%= link_to "Edit this attendance", edit_attendance_path(@attendance) %> |
  <%= link_to "Back to attendances", attendances_path %>

  <%= button_to "Destroy this attendance", @attendance, method: :delete %>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "container") do |form| %>
  <% if event.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 col-2">
    <%= form.label :start_date, class: "form-label" %>
    <%= form.datetime_field :start_date, class: "form-control" %>
  </div>

  <div class="mb-3 col-3">
    <%= form.label :duration, class: "form-label" %>
    <%= form.number_field :duration, class: "form-control" %>
  </div>

  <div class="mb-3 col-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3 col-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3 col-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="mb-3 col-3">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>


<body data-turbo="false">

  <div class="container">
    <h1 class="display-6"> Are you ready to dance ? <%#= current_user.first_name%> </h1>
      <div id="events">
        <% @events.each do |event| %>
          <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                  <p class="card-text"><%= event.description %></p>
                <a href="<%= event_path(event) %>" class="btn">
                  <button type="button" class="btn btn-dark">Voir plus</button>
                </a>
              </div>
          </div>
        <% end %>
      </div>
  </div>

<%= link_to "New event", new_event_path %>


</body>

app/views/events/new.html.erb
<main class= "container">
<h1>Create new event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

</main>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event4UDevise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

<body>
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>"><h1 class="display-5"> Event4U </h1></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_event_path %>">Create event</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Log in/out
            </a>
            <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a></li>
              <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit email / password</a></li>
              <li><a class="dropdown-item" href="<%= users_path(current_user) %>">Profil</a></li>
                <% else %>
              <li><a class="dropdown-item" href="<%= new_user_session_path %>">Log in</a></li>
              <li><a class="dropdown-item" href="<%= new_user_registration_path %>">Registration</a></li>
                <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<h1>Users </h1>

<center>
<h1> Ton profil </h1>
<br>
<p> Prénom : <%= @user.first_name %></p>
<p> Nom de famille : <%= @user.last_name %></p>
<p> Description : <%= @user.description %></p>
<p> E-mail de contact : <%= @user.email %></p>
<p> Date de création du compte : <%= @user.created_at %></p>
<br>
<p> Tes évènements : </p>

<% @user.events.each do |event| %>
  <%= event.title %> : <%= link_to "Voir l'évènement", event_path(event) %> </br>
<% end %>

<%= link_to "Edition du compte", edit_user_registration_path(current_user) %>
</center>